# Generated by Django 6.0.2 on 2026-02-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_clickedurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='request_id',
        ),
    ]
